### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by BraunreutherA** [daheim/daheim-app#1]
Hi, 

I tried to help the daheim team by replacing some buttons they asked me to. 
Actually I can't start the daheim app. 

I installed the npm modules (node version 6.2.2 npm 3.9.5), docker is up to date and running the mongodb container. It seams the ui can't find the react packages.

```bash
/Users/***/Desktop/***/daheim-app/packages/daheim-app-ui/node_modules/react/lib/ReactMount doesn't exist (directory default file)
[ui] [0]   looking for modules in /Users/***/Desktop/***/daheim-app/node_modules
```

I think the paths won't get resolved correctly by using the overall start command in the top level of the project `$ npm run dev`.

Could you please provide more documentation to start up the app locally for a easier start for other developers? 

Best 
Alex

**Comment by egergo** [comment]
You are absolutely right, I'll add a getting started guide.

**Comment by egergo** [comment]
This looks like the breaking change that Facebook introduced in the newest _minor_ version of React. Let me try fixate the versions under this one to give libraries more time to catch up.

**Comment by egergo** [comment]
Please delete everything and clone the repo again. I just did it now and it works. Most likely there are some old npm modules stuck.
